
tasks:
  - init: yarn install
    command: yarn redwood dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8910
    onOpen: open-preview
  - port: 8911
    onOpen: open-preview

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - mgmcdermott.vscode-language-babel
    - wix.vscode-import-cost
    - pflannery.vscode-versionlens
    - editorconfig.editorconfig
    - prisma.prisma
    - graphql.vscode-graphql
